chats/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('chats', views.chats, name='chats'),
    path('chat/def', views.default, name='def'),
    path('chat/<int:reciid>/<int:userid>/<int:name>/<int:is_user>', views.chat, name='chat'),
    path('calls', views.calls, name='calls'),
    path('chat/members/<int:groupId>', views.member, name='member'),
    path('chat/r_member/<int:groupId>', views.r_member, name='r_member'),
    path('media/<path:path>/', views.serve_media, name='serve_media'),
    path('chat/media/<int:mediaId>/', views.media, name='media'),
    path('chat/emoji', views.entertainment, name='entertainment')
]

main/urls.py
from django.urls import path, reverse
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('sign-up', views.sign_up, name='sign_up'),
    path('create-post', views.create_post, name='create_post'),
    #path('logout', auth_views.LogoutView.as_view(template_name="main/base.html", next_page="login"), name='logout')
    #path('logout', views.logout_view, name='logout')
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('chats.urls'))
]

chats/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone



class Chat(models.Model):
    participants = models.ManyToManyField(User, through='ChatParticipant')




class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE, default=0)
    message = models.TextField()
    sent_at = models.DateTimeField()
    status = models.CharField()
    image = models.ImageField(upload_to='dm_media/', blank=True, null=True)
    image_url = models.URLField(blank=True)
    is_video = models.BooleanField(default=False)
    reply = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')



    """def save(self, *args, **kwargs):
        if self.image:
            file_extension = self.image.name.split('.')[-1].lower()
            if file_extension in ['mp4', 'webm', 'avi', 'mov', 'mkv']:
                self.is_video = True
                super().save(*args, **kwargs)"""


class ChatParticipant(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    last_message = models.ForeignKey(Message, on_delete=models.SET_NULL, null=True, blank=True)
    is_blocked = models.BooleanField(default=False)



class Group(models.Model):

    group_name = models.CharField(max_length=30)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class groupprofile(models.Model):
    group = models.OneToOneField(Group, on_delete=models.CASCADE)
    group_picture = models.ImageField(upload_to="dm_media", null=True, blank=True)
    is_user = models.BooleanField(default=False)

class GroupMembers(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    members = models.ForeignKey(User, on_delete=models.CASCADE)
    is_admin = models.BooleanField(False)
    added_at = models.DateTimeField(auto_now_add=True)
    added_by = models.IntegerField()

    def __str__(self):
        return self.members

class GroupMessages(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    message = models.TextField(max_length=5000)
    sent_by = models.ForeignKey(User, on_delete=models.CASCADE)
    sent_at = models.DateTimeField()
    status = models.CharField()
    image = models.ImageField(upload_to='dm_media/', blank=True, null=True)
    image_url = models.URLField(blank=True)
    is_video = models.BooleanField(default=False)

    def __str__(self):
        return self.message

class Recent(models.Model):
    sender = models.IntegerField()
    recipient_id = models.IntegerField()
    user_id = models.IntegerField()
    message = models.TextField()
    sent_at = models.DateTimeField(auto_now_add=True)
# Create your models here.

chats/views.py
import os
from main.models import UserProfile
from django.contrib.auth.decorators import permission_required, login_required
from django.db.models import Q, F
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils import timezone

from website import settings
from .models import Message, Group, GroupMembers, GroupMessages, Chat, ChatParticipant
from django.contrib.auth.models import User
import pytz


@login_required(login_url="/login")
@permission_required("chats.add_message", raise_exception=True)
def chats(request):
    if request.method == 'POST':
        groupName = request.POST.get('group-name')

        Group.objects.create(group_name=groupName, created_by=request.user)
        groups = Group.objects.all().filter(group_name=groupName)[0]
        GroupMembers.objects.create(group=groups, members=request.user, is_admin=True, added_by=request.user.id)


    return render(request, 'chats.html')



def calls(request):
    if request.method == 'POST':
        reci = request.POST.get('seen')
        Message.objects.filter(Q(sender=reci)&Q(recipient_id=request.user.id)).update(status="seen")




    users = User.objects.all().values(
        p_pu = F("userprofile__profile_picture"),
        user_name = F("username"),
        user_id = F("id"),
        users = F("userprofile__is_user")
    ).union(
        Group.objects.filter(groupmembers__members=request.user).values(
            p_pu = F("groupprofile__group_picture"),
            groupname = F("group_name"),
            group_id = F("id"),
            users = F("groupprofile__is_user")
        ))

    return render(request, 'calls.html', {"users": users})

def chat(request, reciid, userid, name, is_user):
    recipient = User.objects.get(id=reciid)
    get = Message.objects.filter(id=name)
    chat = Chat.objects.filter(participants=recipient).filter(participants=request.user)
    #chat_get = Chat.objects.get(participants=recipient).get(participants=request.user)
    present = GroupMessages.objects.filter(group_id=reciid)


    if not chat.exists():
        nc = Chat.objects.create()
        ChatParticipant.objects.create(user=request.user, chat=nc)
        ChatParticipant.objects.create(user=recipient, chat=nc)

    selected = Message.objects.filter(chat=chat[0]).order_by('sent_at')
    if reciid and userid:
        Message.objects.filter(Q(sender=recipient) & Q(chat=chat[0])).update(status="seen")

    else:
        pass

    user_timezone = pytz.timezone('CET')
    if is_user == 1:
        reci = User.objects.all().filter(id=reciid)[0]
    else:
        reci = Group.objects.all().filter(id=reciid)[0]

    if request.method == 'POST':
        form_type = request.POST.get('form_type')
        group_id = request.POST.get("del-b")
        cr = ChatParticipant.objects.filter(Q(chat=chat[0]) & Q(user=recipient))
        if form_type == 'form4':
            reply = request.POST.get("reply")
            copy = request.POST.get("copy")
            delete = request.POST.get("delete")

            if reply:
                get = Message.objects.filter(id=reply)
            elif copy:
                get = Message.objects.filter(id=copy)
                pass
            elif delete:
                Message.objects.filter(id=delete).delete()
        elif form_type == 'form2':
            msg = request.POST.get('r-message')
            img = request.FILES.get('imgs')
            message = Message()
            if is_user == 1:

                if cr[0].is_blocked == False:
                    message.message = msg
                    message.chat = chat[0]
                    message.sender = request.user
                    message.status = "Delivered"
                    message.sent_at = timezone.now().astimezone(pytz.timezone('CET'))
                    message.image = img
                    trying = str(message.image)
                    if trying[-3:] in ['mp4', 'webm', 'avi', 'mov', 'mkv'] or trying[-4:] in ['mp4', 'webm', 'avi', 'mov', 'mkv']:
                        message.is_video = True
                    message.image_url = f"{message.image.name}"
                    if get:
                        message.reply = get[0]

                    message.save()
                    return redirect(f'/chat/{reciid}/{userid}/0/{is_user}')

            else:
                gms = GroupMessages()
                groups = Group.objects.get(id=reciid)
                gms.group = groups
                gms.message = msg
                gms.sent_by = request.user
                gms.status = "Delivered"
                gms.sent_at = timezone.now().astimezone(user_timezone)
                gms.image = img
                g_trying = str(gms.image)
                if g_trying[-3:] in ['mp4', 'webm', 'avi', 'mov', 'mkv'] or g_trying[-4:] in ['mp4', 'webm', 'avi', 'mov', 'mkv']:
                    gms.is_video = True

                gms.save()
                return redirect(f'/chat/{reciid}/{userid}/0/{is_user}')
        elif form_type == 'form1':
            group = Group.objects.get(id=group_id)
            if group:
                try:
                    group_member = GroupMembers.objects.get(group=group, members=request.user)

                    if group_member.is_admin:
                        group.delete()
                except GroupMembers.DoesNotExist:
                    pass
            else:
                pass
        elif form_type == 'form3':
            cr.update(is_blocked=True)


    if is_user == 0:
        gm = GroupMembers.objects.filter(group=reci)
    else:
        gm = []
    return render(request, 'chat.html', {'message': selected, 'groupmessages': present,'reci': reci, 'reply': get , 'r': reciid,'i_u': is_user,'gm': gm})

def default(request):
    return render(request, "def.html")

def member(request,groupId):
    users = User.objects.all()

    if request.method == "POST":
        user = request.POST.getlist("member-id")
        group = Group.objects.all().filter(id=groupId)[0]
        cu = GroupMembers.objects.all().filter(Q(members=request.user)&Q(group_id=groupId))[0]
        if cu.is_admin:
            for sUser in user:

                gm = GroupMembers.objects.all().filter(Q(members_id=sUser)&Q(group_id=groupId))
                if not gm:
                    userId = User.objects.all().filter(id=sUser)[0]
                    GroupMembers.objects.create(group=group,members=userId,is_admin=False,added_by=request.user.id)
                else:
                    pass
        else:
            pass

    return render(request, "group-admins.html", {"users": users,"id": groupId})
def r_member(request,groupId):

    gm = GroupMembers.objects.filter(group_id=groupId)
    if request.method == 'POST':
        ft = request.POST.get("form_type")
        if ft == "form1":
            n = request.POST.get("rm")
            u = GroupMembers.objects.get(Q(members_id=n)&Q(group_id=groupId))
            u.delete()
        elif ft == "form2":
            n = request.POST.get("rm")

            GroupMembers.objects.filter(Q(members_id=n) & Q(group_id=groupId)).update(is_admin=True)

    return render(request, 'group-members.html', {"gm":gm, "id": groupId})
def serve_media(request, path):
    media_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(media_path):
        with open(media_path, 'rb') as f:
            return HttpResponse(f.read(), content_type='image/jpeg')
    return HttpResponse('Image not found',status=404)

def media(request,mediaId):
    mFactor = Message.objects.filter(id=mediaId)
    if mFactor:
        m = Message.objects.get(id=mediaId)
    else:
        m = GroupMessages.objects.get(id=mediaId)
    return render(request, 'media.html',{'mFactor': m})

def entertainment(request):
    
    return render(request, "emoji.html")
    # Create your views here.

chats/templates/base.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'chats/style.css' %}">
<script type="text/javascript" src="{% static 'chats/jquery-3.6.0.js'%}"></script>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chat</title>
    <link rel="stylesheet" href="../static/chats/style.css">
    {% block query %}{% endblock %}


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark pos-fixed">
    <div class="container-fluid">
        <div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/home">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/create-post">Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/chats">Chat</a>
                </li>
            </ul>
        </div>
        <div>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <span class="navbar-text">Logged in as {{ user.username }} | </span>
                <li class="nav-item">
                      <form action="{% url 'logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="nav-link">Log Out</button>
                      </form>
                </li>
                <li class="nav-items">
                    <div class="pic">{% if user.userprofile.profile_picture %} <img src="/media/{{ user.userprofile.profile_picture }}" class="p-picture"> {% else %} {{user.id}} {% endif %}</div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="/login">Login</a>
                </li>
                {% endif %}
            </ul>

        </div>
    </div>
    </nav>
    {% block content %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

chats/templates/calls.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'chats/style.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!--<link rel="stylesheet" href="../static/chats/style.css">-->
</head>
<body>
<div class="inners">
    {% for call in users %}
    {% if call.user_id != user.id %}
        {% if call.users %}
        <a href="chat/{{call.user_id}}{{call.group_id}}/{{user.id}}/0/1" class="link" target="iframes2"><div class="reci-id" data-my-value="{{call.user_id}}{{call.group_id}}">
        {% else %}
        <a href="chat/{{call.user_id}}{{call.group_id}}/{{user.id}}/0/0" class="link" target="iframes2"><div class="reci-id" data-my-value="{{call.user_id}}{{call.group_id}}">
        {% endif %}
            <div class="picser" data-my-value="{{call.user_id}}{{call.group_id}}">
              {% if call.p_pu %}
              <img src="/media/{{call.p_pu}}" class="pp">
              {% else %}
              {{ call.user_id }}{{call.group_id}}
              {% endif %}
            </div>

          <div class="all-conts" data-my-value="{{call.user_id}}{{call.group_id}}">
            <div class="name" data-my-value="{{call.user_id}}{{call.group_id}}">
              {{call.user_name}}{{call.groupname}}
            </div>
            <div class="last-message" data-my-value="{{call.user_id}}{{call.group_id}}">
              Last Message
            </div>
          </div>
        </div>
        </a>

    {% endif %}
{% endfor %}
  </div>
<script>



    document.addEventListener('click', function(event) {
  
    if (event.target.tagName === 'DIV') {
    
      const dataMyValues = event.target.getAttribute('data-my-value');
      console.log(dataMyValues)
      const divs = document.querySelectorAll('.reci-id');
divs.forEach(div => {
  const dataMyValue = div.getAttribute('data-my-value');
  if (dataMyValue === dataMyValues) {
    div.style.backgroundColor = 'rgba(31, 37, 41, 0.25)';
    
  } else {
    div.style.backgroundColor = 'transparent'
    div.style.hover.backgroundColor = 'rgba(31, 37, 41, 0.02)'
  }
  div.style.hover = 'rgba(31, 37, 41, 0.2)';
});
    }


  

});

  




</script>
</body>
</html>

chats/templates/chats.html
{% extends 'base.html' %} {% block title %}Chats{% endblock %}
{% block query %}

   <script>
        $(document).ready(function() {
          $('.addGroup').click(function() {
            $('.toggles').show()
          });
          $('.group-pop-btn').click(function() {
            $('.toggles').hide()
          }

          );
        })
    </script>{% endblock %}
{% block content %}
<div class="toggles">
  <div class="back-fade">
</div>
<div class="group-pop-back">
  <div class="group-pop-cont">
    <form method="post" class="forms">
      {% csrf_token %}
      <input type="text" placeholder="Enter Group name" class="group-pop-input" name="group-name">
      <button type="submit" class="group-pop-btn">Create Group</button>
    </form>
  </div>
</div>
</div>

<div class="conts">
  <iframe class="iframes" src="calls" name="iframes">

  </iframe>
<div class="addGroup">Add Group</div>
  <div class="inners2">
      <iframe src="chat/def" class="iframes2" name="iframes2">
      </iframe>
  </div>
</div>
{% endblock %}

chats/templates/def.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'chats/style.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>

</head>
<body>
  <div class="def">
    Let the Chatting Begin!!
  </div>
</body>
</html>

chats/templates/emoji.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'chats/style.css' %}">
  <title>Title</title>
</head>
<body>
  <div class="emoji">
    <h2 class="emoji-class">Emoji's</h2>
    <div class="emoji-cont" id="emoji-buttons">
      
      
      
    </div>
  </div>
  <script>
    let animals = [
  "\uD83D\uDC31", "\uD83D\uDC30", "\uD83D\uDC34", "\uD83D\uDC35", "\uD83D\uDC36"
]




let food = [
  "\uD83C\uDF54", "\uD83C\uDF55", "\uD83C\uDF56", "\uD83C\uDF57", "\uD83C\uDF58"
];


let objects = [
  "\uD83D\uDCBB", "\uD83D\uDCBC", "\uD83D\uDCBD", "\uD83D\uDCBE", "\uD83D\uDCBF"
];


let flags = [
  "\uD83C\uDDF1\uDDF2", "\uD83C\uDDF2\uDDF3", "\uD83C\uDDF3\uDDF4", "\uD83C\uDDF4\uDDF5", "\uD83C\uDDF5\uDDF6"
];

let people = [
  "\uD83D\uDC68", "\uD83D\uDC69", "\uD83D\uDC66", "\uD83D\uDC67", "\uD83D\uDC66", "\uD83D\uDC65", "\uD83D\uDC67"
];

let symbols = [
  "\u2764", "\u0268", "\uD83D\uDC4D", "\uD83D\uDC4E", "\uD83D\uDC4C"
];

let transportation = [
  "\uD83D\uDE81", "\uD83D\uDE82", "\uD83D\uDE83", "\uD83D\uDE84", "\uD83D\uDE85"
];

let nature = [
  "\uD83C\uDF3C", "\uD83C\uDF3D", "\uD83C\uDF3E", "\uD83C\uDF3F", "\uD83C\uDF40"
];


    let bad = '';
    animals.forEach((x) => {
      bad += `
          <button class="emoji-icon" data-emoji="${x}">${x}</button>
      `  

    })
    food.forEach((x) => {
      bad += `
          <button class="emoji-icon" data-emoji="${x}">${x}</button>
      `  

    })
    objects.forEach((x) => {
      bad += `
          <button class="emoji-icon" data-emoji="${x}">${x}</button>
      `  

    })
    flags.forEach((x) => {
      bad += `
          <button class="emoji-icon" data-emoji="${x}">${x}</button>
      `  

    })
    people.forEach((x) => {
      bad += `
          <button class="emoji-icon" data-emoji="${x}">${x}</button>
      `  

    })
    symbols.forEach((x) => {
      bad += `
          <button class="emoji-icon" data-emoji="${x}">${x}</button>
      `  

    })
    transportation.forEach((x) => {
      bad += `
          <button class="emoji-icon" data-emoji="${x}">${x}</button>
      `  

    })
    nature.forEach((x) => {
      bad += `
          <button class="emoji-icon" data-emoji="${x}">${x}</button>
      `  

    })
    document.querySelector('.emoji-cont').innerHTML = bad
  </script>
</body>
</html>

chats/templates/group-admins.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'chats/style.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

</head>
<body>

    <nav class="navs">
      <a href="/chat/r_member/{{id}}"><div class="items">Members</div></a>
      <div class="items">|</div>
      <a href="/chat/members/{{id}}"><div class="items">Add Members</div></a>
    </nav>
   <div>
    <form method="post" class="pick-m1">
      {% csrf_token %}
      {% for x in users %}
      {% if not x.groupmembers_set.exists %}

      <div class="pick-m2"><input type="checkbox" class="check" value="{{x.id}}" name="member-id"><label class="members">{{x.username}}</label></div>

      {% endif %}
      {% endfor %}
      <button type="submit" class="btn">+</button>
    </form>
  
  </div>

</body>
</html>

chats/templates/group-members.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'chats/style.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

</head>
<body>

    <nav class="navs">
      <a href="/chat/r_member/{{id}}"><div class="items">Members</div></a>
      <div class="items">|</div>
      <a href="/chat/members/{{id}}"><div class="items">Add Members</div></a>
    </nav>

    <div class="big">
      {% for gm in gm %}

    <div class="form-gm"><div class="user-gm">{{ gm.members.username }}</div><form method="post">{% csrf_token %}<input type="hidden" name="form_type" value="form2"><button type="submit" class="add-m" name="rm" value="{{ gm.members.id }}">Add to Admin..</button></form><form method="post"><input type="hidden" name="form_type" value="form1">{% csrf_token %}<button type="submit" class="delete-m" name="rm" value="{{ gm.members.id }}">Remove..</button></form></div>

    {% endfor %}
    </div>


</body>
</html>

chats/templates/media.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'chats/style.css' %}">
  <title>Title</title>
</head>
<body>
  <nav class="nav-media">
    <div class="reci-name">{{mFactor.recipient.username}}{{mFactor.sent_by.username}}</div>
    <div class="b-cont">
      <button class="zoom-in" onclick="zoomIn()">+</button>
      <button class="zoom-out" onclick="zoomOut()">-</button>
    </div>
  </nav>
  <div class="body">
    {% if mFactor.is_video %}

        <video class="imgOut" controls>
          <source src="\media\{{ mFactor.image }}" type="video/mp4">
          Your Browser does not support the video
        </video>

    {% else %}
    <img class="imgOut" src="\media\{{mFactor.image}}">
    {% endif %}
    {% if mFactor.message %}
    <div class="comment">{{mFactor.message}}</div>
    {% endif %}
  </div>
<script>
  let height = 100
  function zoomIn() {
    height += 15
    document.querySelector('.imgOut').style.height = `${height}%`
  }
  function zoomOut() {
    if (height >= 100) {
    height -= 15
    document.querySelector('.imgOut').style.height = `${height}%`
    }
  }
</script>
</body>
</html>